### ISSUE TITLE
gpu_power stays at 0W on AMDGPU

### ISSUE THREAD

**Issue by Lassebq** [flightlessmango/MangoHud#1202]
**Describe the bug**
gpu_power shows no power draw in the overlay - it just stays at 0W

**List relevant hardware/software information**
- Arch Linux
- MangoHud 0.7.0
- GPU AMD Radeon RX 580 (Polaris)

**Expected behavior**
The stat is shown and updated in real time

**Screenshots**
![image](https://github.com/flightlessmango/MangoHud/assets/68742864/3c631426-c84c-43fd-8772-4ed94f3d8cff)
![image](https://github.com/flightlessmango/MangoHud/assets/68742864/e86a083e-e9c5-4879-91b2-5e132fb9bdc6)

**Additional context**
LACT (Linux AMDGPU Controller) shows power draw properly

**Comment by Umio-Yasuno** [comment]
This issue is due to changes in the AMDGPU driver.
https://gitlab.freedesktop.org/drm/amd/-/issues/2897

**Comment by Lassebq** [comment]
Tested with lts kernel (which is 6.1.69 on arch linux), and it does read thermal sensors there. However the performance seems to be significantly worse

**Comment by flightlessmango** [comment]
@Umio-Yasuno I don't fully understand the situation. Currently for these older cards we're getting the power from hwmon, so does sensors/hwmon need to be updated or does mangohud need to use another method?

**Comment by Umio-Yasuno** [comment]
MangoHud need to support `power1_input` for some AMD APU/GPUs.

https://www.kernel.org/doc/html/latest/gpu/amdgpu/thermal.html#hwmon-interfaces

**Comment by flightlessmango** [comment]
Shouldn't `power1_average` still work then?

**Comment by Umio-Yasuno** [comment]
> Shouldn't `power1_average` still work then?

No. Some AMD APUs/GPUs only support `power1_input (AMDGPU_PP_SENSOR_GPU_INPUT_POWER)`, and fallback is not implemented in hwmon interface.  
On the other hand, there are APU/GPUs that support both `power1_average` and `power1_input`. (e.g. VanGogh APU, Phoenix APU, SMU v14.0.0 APU,)

**Comment by flightlessmango** [comment]
@Lassebq this should be fixed here c33ce2b734856934f53721eeffe421b1da0fb935

**Comment by Lassebq** [comment]
Yep, the commit fixes the issue

**Comment by Hcode00** [comment]
was the commit not included in the v0.8.2 release?
i use the arch linux package and i still have the problem but using the mangohud-git package works fine
UPDATE: the git version also does not work. i expected it to work before trying since it used to work a  couple of month ago.
