### ISSUE TITLE
MangoHud git is showing above 100% fan RPM in horizontal mode

### ISSUE THREAD

**Issue by mmbossoni** [flightlessmango/MangoHud#1241]
**Describe the bug**
Mangohud is showing fan rpm with a % symbol even though the value seems to be the actual RPM, not the percentage

**List relevant hardware/software information**
- Linux Distribution: Arch
- MangoHud version: 0.7.1.r11.g3dfd772-1
- GPU: AMD RX 6750XT

**To Reproduce**
1. Add gpu_fan into config

**Expected behavior**
Either show RPM without % or show the actual percentage value

**Comment by mmbossoni** [comment]
![Screenshot_20240218_112027](https://github.com/flightlessmango/MangoHud/assets/7592175/812b37dc-8141-4551-b4bf-64fa2f7185ab)
[Uploadin
[MangoHud.conf.tar.gz](https://github.com/flightlessmango/MangoHud/files/14322833/MangoHud.conf.tar.gz)
g MangoHud.conf…]()

**Comment by Contez** [comment]
I'm not sure if it can be of help, but from a quick search it seems that in ./src/hud_elements.cpp, from line 250
 
```
       if (HUDElements.vendorID == 0x1002 || HUDElements.vendorID == 0x10de){
            if (HUDElements.params->enabled[OVERLAY_PARAM_ENABLED_gpu_fan] && cpuStats.cpu_type != "APU"){
                ImguiNextColumnOrNewRow();
                right_aligned_text(text_color, HUDElements.ralign_width, "%i", gpu_info.fan_speed);
                ImGui::SameLine(0, 1.0f);
                if (gpu_info.fan_rpm) {
                    ImGui::PushFont(HUDElements.sw_stats->font1);
                    HUDElements.TextColored(HUDElements.colors.text, "RPM");
                } else if (HUDElements.vendorID == 0x1002) {
                    HUDElements.TextColored(HUDElements.colors.text, "%%");
                    ImGui::PushFont(HUDElements.sw_stats->font1);
                    ImGui::SameLine(0, 1.0f);
                    HUDElements.TextColored(HUDElements.colors.text, "FAN");
                }
                ImGui::PopFont();
            }
        }
```

So the value unit is set as percentage if the vendor ID is set to AMD (0x1002) or the variable gpu_info.fan_rpm is not set to true in file ./src/gpu.cpp, which for AMD GPUs would be this block below from line 123

```
    if (amdgpu.fan) {
        rewind(amdgpu.fan);
        fflush(amdgpu.fan);
        if (fscanf(amdgpu.fan, "%" PRId64, &value) != 1)
            value = 0;
        gpu_info.fan_speed = value;
        gpu_info.fan_rpm = true;
    }
```

**Comment by flightlessmango** [comment]
I had made a mistake when rewriting this, this should resolve it c80c2093cc20a574e55e815d23f0076c0c80b6a1

**Comment by mmbossoni** [comment]
Just tested new arch packages
Fan still show % RPM instead of just RPM

**Comment by Contez** [comment]
> Just tested new arch packages Fan still append % for RPM

@mmbossoni is it already compiled from HEAD, with the latest commit? From [Arch repository](https://archlinux.org/packages/?name=mangohud) I see that it is still the last release, uploaded on 8th of February.

**Comment by Contez** [comment]
> Yes, it is. I use mangohud-git package (from AUR)

Unless I'm missing something (which is totally possible😉 ) [mangohud-git](https://aur.archlinux.org/packages/mangohud-git) is a bunch of commits behind, specifically, as of today, still at commit [48d8426](https://github.com/flightlessmango/MangoHud/commit/48d84262cd21ae3916e2d9713b9f1a223190b1a6) from Feb 7th, so not aligned with the lastest commit.

**Comment by mmbossoni** [comment]
-git packages on aur work a bit differently
Every time you rebuild it, it will checkout the latest commit and build from there.
So the commit you see on the package isn't actually the commit it will build
Maintainers only update the commit when they need to change the spec (PKGBUILD) file due to some dependency change

**Comment by Contez** [comment]
Understood, thank you for the explanation.I am not familiar with Arch and AUR, so I was not aware of that, good to know. 😉… and it seems the issue still persists then.On 20 Feb 2024, at 17.56, mmbossoni ***@***.***> wrote:﻿
-git packages on aur work a bit differently
Every time you rebuild it, it will checkout the latest commit and build from there.
So the commit you see on the package isn't actually the commit it will build
Maintainers only update the commit when they need to change the spec (PKGBUILD) file due to some dependency change

**Comment by flightlessmango** [comment]
does this resolve it ? 98e442ba7f860de493a1b48460ef5398715bde2a

**Comment by mmbossoni** [comment]
Yes, that fixes it
