### ISSUE TITLE
mangoapp does not read config files

### ISSUE THREAD

**Issue by NoXPhasma** [flightlessmango/MangoHud#1383]
**Describe the bug**
When I launch gamescope with `--mangoapp` it will not read any config files. Using `MANGOHUD_CONFIG` works, though.

**List relevant hardware/software information**
- Arch Linux
- MangoHud version 0.7.2
- AMD 7800XT

**To Reproduce**
1. Launch gamescope with `--mangoapp`
2. Have a MangoHud.conf file
3. Check the Hud

**Comment by flightlessmango** [comment]
What appears to be happening is that gamescope is creating a temporary config file for mangoapp.
This is similar to what steamos does in `gamescope-session`, but it's not compatible with each other.

@Joshua-Ashton is there a reason to make a temporary file by default like this?
I think normal users would expect the config to work just like mangohud

**Comment by NoXPhasma** [comment]
Gamescope recently enabled the `MANGOHUD_CONFIGFILE` variable with https://github.com/ValveSoftware/gamescope/commit/b44ea3c591f9ed28f5480d1f86936ad63c937077. This works fine, but I assume we should to communicate it somewhere.

**Comment by d3nd3** [comment]
I wanna say that I have a very similar problem.  `MANGOHUD_CONFIG` works, but `MANGOHUD_CONFIGFILE` or creating `~/.config/MangoHud/MangoHud.conf` does not. (Ignore if unrelated.)

**Comment by NoXPhasma** [comment]
@d3nd3 It's the same issue.  `MANGOHUD_CONFIGFILE` only works with a gamescope version, built with [this patch](https://github.com/ValveSoftware/gamescope/commit/b44ea3c591f9ed28f5480d1f86936ad63c937077), you might need to build it from git.

**Comment by zoobporsor** [comment]
ive got the same problem I cant launch mangoapp  using any custom config, i tried mangohud_configfile but cant get it to load either. mangohud_configfile works fine with regular mangohud though.

**Comment by HolySoap** [comment]
So what is the exact procedure and steps to have a working mangoapp with a custom config file?

**Comment by flightlessmango** [comment]
As a workaround you can set `MANGOHUD_CONFIGFILE`

**Comment by HolySoap** [comment]
> As a workaround you can set `MANGOHUD_CONFIGFILE`

Where do I have to put it?

**Comment by flightlessmango** [comment]
It should look something like this
`MANGOHUD_CONFIGFILE=path/to/config gamescope --mangoapp %command%`

**Comment by HolySoap** [comment]
Doesn't work or did I something wrong?
`MANGOHUD_CONFIGFILE=/home/wanderer/.config/MangoHud/MangoHud.conf gamescope -f -e -h 1440 --mangoapp -- %command%`

**Comment by flightlessmango** [comment]
That looks correct assuming there's a config in that location

**Comment by NoXPhasma** [comment]
`MANGOHUD_CONFIGFILE` is only available in gamescope with version [3.14.24](https://github.com/ValveSoftware/gamescope/releases/tag/3.14.24).

**Comment by flightlessmango** [comment]
This issue should be resolved in https://github.com/ValveSoftware/gamescope/commit/96f141d8b8453f9c28872e8ffc94a29d81d0758d

**Comment by HolySoap** [comment]
3.14.24 is exactly what's installed, but still doesn't work.
![Screenshot_2024-07-22_2](https://github.com/user-attachments/assets/13d0a125-ea52-4d2b-80c4-f840f74caa06)

**Comment by flightlessmango** [comment]
This has been resolved in https://github.com/ValveSoftware/gamescope/commit/96f141d8b8453f9c28872e8ffc94a29d81d0758d

**Comment by Letus252** [comment]
Still doesn't work for me on arch dwl wayland mangodhud v0.7.1
