### ISSUE TITLE
Mango Hud does not grab any GPU information on multi-GPU setups

### ISSUE THREAD

**Issue by november781** [flightlessmango/MangoHud#1440]
**Describe the bug**

I have both an RTX 3070 and an AMD 5800XT in my system. All redering is being done on the 5800xt and the 3070 is really just here for the NVENC encoder. However MangoHud has just given up on showing any GPU information since I added the Nvidia card to my system. 

**List relevant hardware/software information**
- Fedora 40
- MangoHud version = 0.7.2
- GPU = RX5800XT and RTX 3070

**To Reproduce**
1. add an extra GPU to a system, probably an AMD + Nvidia issue when not using optimus/prime
2. make sure MangoHud is configured to show GPU data
3. Launch a game

**Expected behavior**
MangoHud should grab GPU details from at least one card if not both, or preferably have a way to specify which card to pull data for

**Screenshots**
![Screenshot_20240923_105613](https://github.com/user-attachments/assets/62d32ad6-189d-47c8-8b25-5623cb64a0bc)

**Additional context**
[MangoHud.conf](https://github.com/user-attachments/files/17099559/MangoHud.txt)

**Comment by gort818** [comment]
Can you test this branch please?
https://github.com/flightlessmango/MangoHud/tree/multi-gpu-attempt

**Comment by november781** [comment]
> Can you test this branch please? https://github.com/flightlessmango/MangoHud/tree/multi-gpu-attempt

Tried building it and running vkcube with the resulting binary and got no change. 

I cloned the repo, switched to the multi-gpu-attempt branch, ran the build script then went into the releases folder and ran the mangohud binary with vkcube. If that is the wrong way to do this please let me know

**Comment by gort818** [comment]
Well the "binary" is basically just a script that sets the environmental variable, I do not believe you are using the newly built library that way.

Can you install it after building it and please try again

**Comment by november781** [comment]
> Well the "binary" is basically just a script that sets the environmental variable, I do not believe you are using the newly built library that way.
> 
> Can you install it after building it and please try again

ran the install portion of the build script and now its just seg faulting 
![image](https://github.com/user-attachments/assets/8c7425c7-fa82-4158-9770-a081e94e3bba)

**Comment by gort818** [comment]
That is odd.. I just pushed a commit that might fix the error above. The fedora repo version should not have the mutli gpu stuff

**Comment by november781** [comment]
Ill check it in the morning when the commit hits github. I'm also gonna see if I cant get back to the state I was at the start of all of this... because even after a reboot I'm still seeing the multi-GPU stuff

**Comment by gort818** [comment]
oh yeah sorry the multi gpu stuff was pushed to master, should just need to build master branch, what errors are you getting trying to build?

**Comment by november781** [comment]
> oh yeah sorry the multi gpu stuff was pushed to master, should just need to build master branch, what errors are you getting trying to build?

its building now, but its core dumping when I try to run now
![image](https://github.com/user-attachments/assets/21e93294-c98a-4fca-b7b1-a21c12102262)

**Comment by flightlessmango** [comment]
This should be resolved in latest master
