### ISSUE TITLE
0.8.2: release tarball issues (wrong version - still at 0.8.1)

### ISSUE THREAD

**Issue by tgurr** [flightlessmango/MangoHud#1871]
**Describe the bug**
https://github.com/flightlessmango/MangoHud/releases/download/v0.8.2/MangoHud-v0.8.2-Source.tar.xz

Contains a directory with the wrong version MangoHud-v0.8.1, and meson.build also contains the wrong version: https://github.com/flightlessmango/MangoHud/blob/v0.8.2/meson.build#L3

**List relevant hardware/software information**
-

**To Reproduce**
- Download https://github.com/flightlessmango/MangoHud/releases/download/v0.8.2/MangoHud-v0.8.2-Source.tar.xz
- See https://github.com/flightlessmango/MangoHud/blob/v0.8.2/meson.build#L3

**Expected behavior**
Have proper versioning.

**Screenshots**
-

**Additional context**
-

**Comment by flightlessmango** [comment]
resolved

**Comment by tgurr** [comment]
> resolved

I can see the version bump happened to the meson.build in master, but is still not part of the v0.8.2 tag/release and release tarball? So the complaints for 0.8.2 are still valid, which still makes it quite an issue for distribution packaging.

**Comment by flightlessmango** [comment]
Now it should be fixed for reals

**Comment by tgurr** [comment]
Thanks!
