### ISSUE TITLE
`gpu_name` displays the incorrect GPU (dGPU instead of the iGPU)

### ISSUE THREAD

**Issue by NerosTie** [flightlessmango/MangoHud#321]
When I launch an application with the iGPU, `gpu_name` should displays `Mesa DRI Intel(R) HD Graphics 4600` or something like this, but instead it displays my dGPU which is not correct:

The OpenGL version, `engine_version`, is correct though.

![Screenshot_20200820_140108](https://user-images.githubusercontent.com/4572452/90768122-8930ec00-e2ee-11ea-9f23-bb62bcf60ddf.png)

```
$ inxi -SMGxx
System:    Host: Neros Kernel: 5.8.1-arch1-1 x86_64 bits: 64 compiler: N/A Desktop: KDE Plasma 5.19.4 tk: Qt 5.15.0 
           wm: kwin_x11 dm: LightDM, SDDM Distro: Antergos Linux 2015.10-ISO-Rolling 
Graphics:  Device-1: Intel 4th Gen Core Processor Integrated Graphics vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:0416 
           Device-2: NVIDIA GK208M [GeForce GT 730M] vendor: Lenovo driver: nvidia v: 450.57 bus ID: 02:00.0 
           chip ID: 10de:1290 
           Device-3: Acer SunplusIT Integrated Camera type: USB driver: uvcvideo bus ID: 2-12:11 chip ID: 5986:0268 
           Display: x11 server: X.Org 1.20.8 compositor: kwin_x11 driver: intel,nvidia unloaded: fbdev,modesetting,vesa 
           alternate: nouveau,nv resolution: 1920x1080~60Hz s-dpi: 96 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) v: 4.5 Mesa 20.1.5 compat-v: 3.0 direct render: Yes 
```

**Comment by flightlessmango** [comment]
There is no good way to detect if it's dgpu or igpu being used, it's a whole mess with prime and all the different versions. The current workaround we're using is to assume if a dgpu exists, it's the one being used

**Comment by NerosTie** [comment]
@flightlessmango Why do you close it? Is it fixed in the dev branch?

**Comment by flightlessmango** [comment]
No this is not solved (at least not intentionally), I got confused by the unrelated comments. However it would be useful if you could test with dev branch and see if anything has changed

**Comment by NerosTie** [comment]
I've just tested with the "develop" branch and it looks like nothing has changed about this issue unfortunately.

**Comment by jarrard** [comment]
I get the below. Needs SUDO in order to work correctly. Don't know why. 

```
[2022-01-27 15:37:30.464] [MANGOHUD] [info] [config.cpp:114] skipping config: '/usr/bin/MangoHud.conf' [ not found ]
[2022-01-27 15:37:30.465] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/theriddick/.config/MangoHud/glxgears.conf' [ not found ]
[2022-01-27 15:37:30.465] [MANGOHUD] [info] [config.cpp:119] parsing config: '/home/theriddick/.config/MangoHud/MangoHud.conf'
[2022-01-27 15:37:30.520] [MANGOHUD] [error] [overlay.cpp:578] Failed to parse PCI device ID: ''0000\:12\:00.0''
[2022-01-27 15:37:30.520] [MANGOHUD] [error] [overlay.cpp:579] Specify it as 'domain:bus:slot.func'
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
[2022-01-27 15:37:30.520] [MANGOHUD] [error] [gpu.cpp:270] Failed to initialize amdgpu device: Permission denied
[2022-01-27 15:37:30.520] [MANGOHUD] [error] [overlay.cpp:642] Failed to open device '/dev/dri/card1' with libdrm, falling back to using hwmon sysfs.
[2022-01-27 15:37:30.520] [MANGOHUD] [info] [overlay.cpp:678] Uploading is disabled (permit_upload = 0)
[2022-01-27 15:37:30.528] [MANGOHUD] [info] [imgui_impl_opengl3.cpp:418] GL version: 4.6
```

**Comment by flightlessmango** [comment]
I believe this should be resolved in latest

**Comment by VortexAcherontic** [comment]
> I believe this should be resolved in latest

I briefly verified this and can confirm that this meanwhile works on my end too :)

Many thanks!
