### ISSUE TITLE
MangoHud in Metro Exodus(native Linux version) shows OpenGL instead of Vulkan.

### ISSUE THREAD

**Issue by xcom169** [flightlessmango/MangoHud#559]
MangoHud in Metro Exodus(native Linux version) shows OpenGL instead of Vulkan.
Also the Mesa version is incorrectly reported. 

Can anybody pls second check this?

**Comment by jackun** [comment]
What version are you on? v0.6.4+ _should_ work and I can't see why it wouldn't if it's already the latest. But I can test when it finishes downloading.

**Comment by flgx16** [comment]
Tag `v0.6.4` shows OpenGL. Latest `master` and `develop` branches show Vulkan.

**Comment by jackun** [comment]
Never mind, memory fails me :P Probably be fixed in next release. But the mesa version, is it running in Steam linux runtime or something like that?

**Comment by xcom169** [comment]
To be honest I'm not sure about the Steam runtime.
First I downloaded the game : It sent 'missing executable'
I switched on : Linux runtime: Missing libinput 1.5
I switched to Proton: Still not working
I switched to Zero compabiltiy layer.: Now it's working, but I think the
Mesa version is not correct. It shows something like 21.1.4 but I have
21.1.3.

**Comment by jackun** [comment]
Dunno, mesa is 21.1.3 for me too but driver is 21.1.4

**Comment by Leopard1907** [comment]
Post this output:

`inxi -SMGxx`

21.1.4 is the latest, a bugfix release.

**Comment by xcom169** [comment]
![image](https://user-images.githubusercontent.com/17802090/124615407-87740680-de75-11eb-990a-386a581c6b56.png)

System:
  Host: csabesz-a320ms2hv2 Kernel: 5.12.9-1-MANJARO x86_64 bits: 64 
  compiler: gcc v: 11.1.0 Desktop: GNOME 3.38.4 tk: GTK 3.24.29 
  wm: gnome-shell dm: GDM Distro: Manjaro Linux base: Arch Linux 
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME A320M-K v: Rev X.0x 
  serial: <superuser required> UEFI: American Megatrends v: 5603 
  date: 10/14/2020 
Graphics:
  Device-1: AMD Vega 10 XL/XT [Radeon RX Vega 56/64] 
  vendor: Sapphire Limited driver: amdgpu v: kernel bus-ID: 0a:00.0 
  chip-ID: 1002:687f 
  Display: x11 server: X.org 1.20.11 compositor: gnome-shell driver: 
  loaded: amdgpu resolution: <missing: xdpyinfo> 
  OpenGL: 
  renderer: Radeon RX Vega (VEGA10 DRM 3.40.0 5.12.9-1-MANJARO LLVM 12.0.0) 
  v: 4.6 Mesa 21.1.4 direct render: Yes

**Comment by xcom169** [comment]
It looks the Vulkan mesa driver versions is always +1 than the actual. Strange..

**Comment by flgx16** [comment]
Both issues (showing OpenGL instead of Vulkan and mesa driver version being +1) should be fixed with MangoHud v0.6.5 release.

**Comment by xcom169** [comment]
You are the best! TY
