### ISSUE TITLE
OpenGL fail "can't get dlopen()"

### ISSUE THREAD

**Issue by CrimsonFork** [flightlessmango/MangoHud#693]
64 bit OpenGL games reliably fail almost immediately with
```
can't get dlopen()
```
as the only terminal output

Ubuntu 21.10, happens with the builds from the Ubuntu repository, latest stable and latest builds from GitHub all the like.

**Comment by rigoleto** [comment]
I encountered this same issue, and upgrading from v0.6.5 to v0.6.6-1 solved it

**Comment by akien-mga** [comment]
I had the same issue too with `v0.6.5`, which is currently shown as the latest release:
![image](https://user-images.githubusercontent.com/4701338/160164516-e5c26c6d-5a6b-474d-826e-0345164ab62d.png)

@flightlessmango I suggest marking all releases as full releases, or all as "pre-release", but not a mix of both (unless `v0.6.6-1` is really not meant to be used instead of `v0.6.5` in a stable environment).

**Comment by flightlessmango** [comment]
Since 0.6.7 is released this should not be an issue

**Comment by johnblommers** [comment]
Confirmed fixed in version 0.6.7 :-)
It also works after upgrading PopOS to 22.04.
Cool.

**Comment by cglmrfreeman** [comment]
Had to remove Mangohud from lutris ages ago because of this issue. Decided to give it another try because I'm seeing weird frame drops. Still have this issue.

**Comment by flightlessmango** [comment]
@cglmrfreeman If you scroll up you can see that it's been fixed, you're using an old version of mangohud.

**Comment by flightlessmango** [comment]
Since it's been fixed, we're unable to reproduce it. So some information could be useful like: what version of mangohud exactly are you on, what games/apps have you tried with, what OS are you using etc.

**Comment by jackun** [comment]
@cglmrfreeman if you see only `can't get dlopen()`, you don't have latest version installed. Latest should print `MANGOHUD: Can't get dlopen()` but hopefully it's fixed for glibc >= 2.34.

**Comment by cglmrfreeman** [comment]
Well, I just tested `mangohud glxgears` and it ran. So it's an unrelated issue that's causing `can't get dlopen()` with mangohud via lutris.

**Comment by jackun** [comment]
Maybe there's somehow some other version installed somewhere and lutris picks it up.

**Comment by cglmrfreeman** [comment]
> Maybe there's somehow some other version installed somewhere and lutris picks it up. `LD_DEBUG=libs` :P

Wow this log contains some straight up nonsense. What the heck is lutris even doing?! [ow-mangohud-log.log](https://github.com/flightlessmango/MangoHud/files/8780995/ow-mangohud-log.log)

OS: openSUSE Tumbleweed 20220516
Kernel: x86_64 Linux 5.17.7-1-default
Lutris: lutris-0.5.10.1
mangohud (and 32 bit ver): 0.6.7~1-1.1

**Comment by jackun** [comment]
Should be fine, but if this gives you trouble then your 32bit MangoHud seems to be out of date.

**Comment by jackun** [comment]
Yeah, i think you have old release package installed. Nuke the `/usr/lib/mangohud` and reinstall the packages.

**Comment by cglmrfreeman** [comment]
That is like, really, really, _really_ stupid that that worked :facepalm:. I had always assumed uninstalling and reinstalling packages would remove such data, but apparently not. Is there some documentation where it says this folder may need refreshing?

**Comment by jackun** [comment]
Random tar file is not managed distro's package manager. You install, you yourself uninstall it too :P

**Comment by cglmrfreeman** [comment]
I have never installed mangohud manually as far as I know, if that's the random tar you are speaking of. Even if that was the case, why would the package manager not overwrite on install of a package? If the distro package manager knew it wasn't installed by itself, why would it say successful installation once it tried to install it's own managed version from a repo? I'm finding this situation extremely absurd and wanting to begin auditing every binary I have "installed".

**Comment by 19s-fautley-k** [comment]
mangohud in the Ubuntu repos is still 0.6.5-2 btw
