### ISSUE TITLE
Horizontal style showing magenta separators

### ISSUE THREAD

**Issue by mmbossoni** [flightlessmango/MangoHud#949]
I was just trying new horizontal style from git, but I'm getting some magenta separators.
Is this a bug or some wrong configuration.
It is like Mangohud is creating the slot for each of the available displayable stuff, but if that is not enabled, a separator is drawn instead.

![Screenshot_20230311_175431](https://user-images.githubusercontent.com/7592175/224511239-9e0eb258-321b-4ed3-8ef5-25b92d5933e0.png)

**Comment by mmbossoni** [comment]
OK, seems like I have to enable legacy layout... is that expected?

**Comment by flightlessmango** [comment]
That's a bug for sure. Can you post your full config?

**Comment by mmbossoni** [comment]
[MangoHud.conf.tar.gz](https://github.com/flightlessmango/MangoHud/files/10949495/MangoHud.conf.tar.gz)
If I enable legacy layout, separators go away
Just as an extra step: I copied the base config from github and added the missing bits looking at the code, so it could be my fault as well.

**Comment by jazztickets** [comment]
For me the bug occurs with certain offset_y values:
![offset](https://user-images.githubusercontent.com/425930/229575856-c92db4c5-9ec5-498d-9e09-e4d2f220fd18.png)

Anything below offset_y=16 at font size 13 shows the bars.

Config:

```
horizontal
table_columns=25
cpu_temp=1
gpu_temp=1
vram=0
ram=0
frame_timing=0
background_alpha=0
font_size=13
position=top-left
offset_y=12
offset_x=16
time=1
time_format=%I:%M %p
```

**Comment by mmbossoni** [comment]
For me it always happen, maybe because I'm using hud_no_margin, that basically set offset_y to 0?

**Comment by vanphong1310** [comment]
Why in horizontal mode it only show "FPS" text instead of engine name like normal mode?

**Comment by flightlessmango** [comment]
This should be fixed in latest

**Comment by ceLoFaN** [comment]
~This seems to be happening again v0.8.2.~

Eh it was caused by:
```
vram=0
ram=0
```
I removed those and the extra separators are gone now...

**Comment by Rebl11** [comment]
> ~This seems to be happening again v0.8.2.~
> 
> Eh it was caused by:
> 
> ```
> vram=0
> ram=0
> ```
> 
> I removed those and the extra separators are gone now...

In your case I'd do

```
#vram
#ram
```
This way it still exists in the config file but doesn't make the separators appear.
